version: "3.4"

services:
    shipmonk-packing-mysql:
        image: mariadb:10.7
        ports:
            -
                target: 3306
                published: 3306
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: packing
        hostname: mysql

    shipmonk-packing-app:
        build: .
        working_dir: /app
        user: ${UID:-1000}:${GID:-1000}
        volumes:
          - .:/app

    shipmonk-packing-adminer:
        image: adminer:latest
        ports:
            -
                target: 8080
                published: 8080
